accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name= 'accounts'

urlpatterns = [
    # path('signup/', views.SignUp.as_view(), name='signup'),
    path('signup_step1/', views.signup_step1, name='signup_step1'),
    path('signup_step2/', views.signup_step2, name='signup_step2'),
    path('signup_step3/', views.signup_step3, name='signup_step3'),
    path('signup_step4/', views.signup_step4, name='signup_step4'),
    path('signup_step3_update/', views.signup_step3_update, name='signup_step3_update'),
    path('signup_step4_update/', views.signup_step4_update, name='signup_step4_update'),
    # path('config/', views.stripe_config, name='stripe_config'),
    # path('create-checkout-session/',views.onetime_payment_checkout , name='create-checkout'),
    # path('complete_mail/', views.complete_mail, name='complete_mail'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('signup_login/', views.Signup_Login.as_view(), name='signup_login'),
    path('terms_service/', views.terms_service, name='terms_service'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
]

imagediff/urls.py
from django.urls import path
from . import views

app_name= 'imagediff'

urlpatterns = [
    path('top/',          views.view_top,    name='top'),
    path('camera/',       views.view_camera, name='camera'),
    path('camera_1send/', views.view_camera_1send, name='camera_1send'),
    path('result/',       views.view_result, name='result'),
    path('config/',       views.view_config, name='config'),
    path('alert/',        views.view_alert,  name='alert'),
    path('alert/csv/',    views.view_csv,    name='csv'),
    path('word/',         views.view_word,  name='word'),
    path('log/',          views.view_log,    name='log'),
    # path('alert/add/', views.alert_add, name='alert_add'),
    # path('alert/edit/', views.alert_edit, name='alert_edit'),
    # path('alert/del/', views.alert_del, name='alert_del'),
    # path('alert/ref/', views.alert_ref, name='alert_ref'),
]

imagediff/models.py
from django.db import models
# from django.core.validators import MaxValueValidator, MinValueValidator 
from django.contrib.auth import get_user_model
from django.utils import timezone

class Config(models.Model):

    user            = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, primary_key=True)
    alert_id        = models.IntegerField(verbose_name="参照ＩＤ")
    email           = models.CharField(max_length=254, verbose_name="メールアドレス")
    match_length    = models.IntegerField(default=3, verbose_name="一致文字数")
    facing_mode     = models.BooleanField(default=1, verbose_name="カメラモード")
    expiration_date = models.DateField(verbose_name="有効期限")
    frequency_limit = models.IntegerField(null=True, blank=True, verbose_name="限度回数")

class Alert(models.Model):

    key           = models.CharField(max_length=80, primary_key=True, verbose_name="キー")
    alert_id      = models.IntegerField(verbose_name="参照ＩＤ")
    alert_word    = models.CharField(max_length=50, verbose_name="警告ワード")
    alert_comment = models.CharField(max_length=254, verbose_name="警告コメント")
    create_user   = models.CharField(max_length=150, verbose_name="作成者")
    created_at    = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    update_user   = models.CharField(max_length=150, verbose_name="更新者")
    updated_at    = models.DateTimeField(auto_now=True, verbose_name="更新日時")

class Log(models.Model):

    key             = models.CharField(max_length=20, primary_key=True, verbose_name="キー")
    log_date        = models.DateTimeField(auto_now_add=True, verbose_name="実行日時")
    user_id         = models.IntegerField(verbose_name="ユーザーＩＤ")
    result          = models.TextField(verbose_name="比較結果")
    image01         = models.TextField(null=True, blank=True, verbose_name="画像01")
    image02         = models.TextField(null=True, blank=True, verbose_name="画像02")

class Word(models.Model):

    key         = models.CharField(max_length=80, primary_key=True, verbose_name="キー")
    alert_id    = models.IntegerField(verbose_name="参照ＩＤ")
    word_before = models.CharField(max_length=1, verbose_name="変換前")
    word_after  = models.CharField(max_length=1, verbose_name="変換後")
    create_user = models.CharField(max_length=150, verbose_name="作成者")
    created_at  = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    update_user = models.CharField(max_length=150, verbose_name="更新者")
    updated_at  = models.DateTimeField(auto_now=True, verbose_name="更新日時")

# class SearchLog(models.Model):

#     start_date = models.DateField(null=True, blank=True, verbose_name="開始日")
#     end_date   = models.DateField(null=True, blank=True, verbose_name="終了日")


imagediff/forms.py
import bootstrap_datepicker_plus as datetimepicker
from django import forms

class SearchLogForm(forms.Form):

    startDate = forms.CharField(
        label="開始日",
        required=True,
        disabled=False,
        widget=datetimepicker.DatePickerInput(
            format="%Y-%m-%d",
            attrs={"readonly": "true", "id": "startDate"},
            options={
                "locale": "ja",
                "dayViewHeaderFormat": "YYYY年 MMMM",
                "ignoreReadonly": True,
                "allowInputToggle": True
            }
        )
    )
    
    endDate = forms.CharField(
        label="終了日",
        required=True,
        disabled=False,
        widget=datetimepicker.DatePickerInput(
            format="%Y-%m-%d",
            attrs={"readonly": "true", "id": "endDate"},
            options={
                "locale": "ja",
                "dayViewHeaderFormat": "YYYY年 MMMM",
                "ignoreReadonly": True,
                "allowInputToggle": True
            }
        )
    )


class UploadCsvFileForm(forms.Form):

    csvfile = forms.FileField(
        label="Step1. CSVファイルアップロード",
        required=False,
        disabled=False,
        widget=forms.FileInput(
            attrs={
                 "class": "form-control",
                 "accept": ".csv",
            },
        )
    )
    
    wordSpaceDelHalf = forms.BooleanField(
        label="空白除去（半角）",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )
    
    wordSpaceDelFull = forms.BooleanField(
        label="空白除去（全角）",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )
    
    wordSpaceFullToHalf = forms.BooleanField(
        label="全角→半角（空白）",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )
    
    wordFullToHalf = forms.BooleanField(
        label="全角→半角（英数字記号）",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )
    
    wordHalfToFull = forms.BooleanField(
        label="半角→全角（カタカナ）",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )
    
    # wordSelectCol = forms.ChoiceField(
    #     label="列指定",
    #     required=False,
    #     disabled=False,
    #     widget=forms.Select(
    #         attrs={
    #             "class": "custom-select",
    #         }
    #     ),
    # )
    
    cmtSpaceDelHalf = forms.BooleanField(
        label="空白除去（半角）",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )
    
    cmtSpaceDelFull = forms.BooleanField(
        label="空白除去（全角）",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )
    
    cmtSpaceFullToHalf = forms.BooleanField(
        label="全角→半角（空白）",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )
    
    cmtFullToHalf = forms.BooleanField(
        label="全角→半角（英数字記号）",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )
    
    cmtHalfToFull = forms.BooleanField(
        label="半角→全角（カタカナ）",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )
    
    # cmtSelectCol = forms.ChoiceField(
    #     label="列指定",
    #     required=False,
    #     disabled=False,
    #     widget=forms.Select(
    #         attrs={
    #             "class": "custom-select",
    #         }
    #     ),
    # )
    
    addAlertDBIndexDel = forms.BooleanField(
        label="見出し行除外",
        required=False,
        disabled=False,
        widget=forms.CheckboxInput(
            attrs={
                "class": "custom-control-input",
            }
        ),
    )

templates/imagediff/config.html
{% extends 'imagediff/base.html' %}
{% load i18n static %}

{% block additional_meta %}
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
{% endblock additional_meta %}

{% block title_name %}Config{% endblock title_name %}

{% block additional_script %}
<script src="{% static 'imagediff/js/config.js' %}"></script>
{% endblock additional_script %}

{% block content %}
{% if messages %}
<ul class="messagelist">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|linebreaksbr }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="" method="post">{% csrf_token %}
    <div class="form-inner">
        <h2 class="display-5">個別設定</h2>

        <hr>

        <div class="form-group">
            <label for="id_username" class="col-form-label-lg mb-0">ユーザー名</label>
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fas fa-user"></i><span>
                </div>
                <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" value="{{ data.0.user_name }}" disabled="disabled">
                <div class="input-group-append">
                    <button type="button" class="btn btn-outline-secondary" data-toggle="modal" data-target="#modal0">パスワード変更</button>
                </div>
            </div>
        </div>

        {% comment %} <label>ユーザー名</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" value="{{ data.0.user_name }}" disabled="disabled">
        </div> {% endcomment %}

        <div class="form-group">                
            <label for="id_username" class="col-form-label-lg mb-0">参照警告ＤＢ</label>                
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fas fa-database"></i><span>
                </div>
                <input type="text" class="form-control" placeholder="AlertDB" aria-label="AlertDB" aria-describedby="basic-addon1" value="{{ data.0.alert_user_name }}" disabled="disabled">
            </div>
        </div>

        {% comment %} <label>参照アラートＤＢ</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="fas fa-database"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="AlertDB" aria-label="AlertDB" aria-describedby="basic-addon1" value="{{ data.0.alert_user_name }}" disabled="disabled">
        </div> {% endcomment %}

        <div class="form-group">
            <label for="id_email" class="col-form-label-lg mb-0">メールアドレス</label>
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="far fa-envelope"></i></span>
                </div>
                <input type="email" class="form-control" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1" value="{{ data.0.email }}" name="email">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-secondary" name="updateEmail">更新</button>
                </div>
            </div>
        </div>

        {% comment %} <label>メールアドレス</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="far fa-envelope"></i></span>
            </div>
            <input type="email" class="form-control" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1" value="{{ data.0.email }}" name="email">
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary" name="updateEmail">更新</button>
            </div>
        </div> {% endcomment %}

        <div class="form-group">
            <label for="inputGroupSelect01" class="col-form-label-lg mb-0">一致文字数</label>
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fas fa-wrench"></i></span>
                </div>                    
                <select class="custom-select" id="inputGroupSelect01" name="matchLength">
                    {% for option in optionList %}                    
                    <option value="{{ option }}" {% if data.0.match_length == option %}selected{% endif %}>{{ option }}</option>
                    {% endfor %}
                </select>
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-secondary" name="updateMatchLength">更新</button>
                </div>
            </div>
        </div>

        {% comment %} <label>一致文字数</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="inputGroupSelect01"><i class="fas fa-wrench"></i></label>
            </div>
            <select class="custom-select" id="inputGroupSelect01" name="matchLength">
                {% for option in optionList %}                    
                <option value="{{ option }}" {% if data.0.match_length == option %}selected{% endif %}>{{ option }}</option>
                {% endfor %}
            </select>
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary" name="updateMatchLength">更新</button>
            </div>
        </div> {% endcomment %}

        <div class="form-group">
            <label for="inputGroupSelect02" class="col-form-label-lg mb-0">カメラモード</label>
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fas fa-camera"></i></span>
                </div>
                <select class="custom-select" id="inputGroupSelect02" name="facingMode">
                    <option value="0" {% if data.0.facing_mode == 0 %}selected{% endif %}>インカメラ</option>
                    <option value="1" {% if data.0.facing_mode == 1 %}selected{% endif %}>バックカメラ</option>
                </select>
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-secondary" name="updateFacingMode">更新</button>
                </div>
            </div>
        </div>

        {% comment %} <label>カメラモード</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <label class="input-group-text" for="inputGroupSelect02"><i class="fas fa-camera"></i></label>
            </div>
            <select class="custom-select" id="inputGroupSelect02" name="facingMode">
                <option value="0" {% if data.0.facing_mode == 0 %}selected{% endif %}>インカメラ</option>
                <option value="1" {% if data.0.facing_mode == 1 %}selected{% endif %}>バックカメラ</option>
            </select>
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary" name="updateFacingMode">更新</button>
            </div>
        </div> {% endcomment %}

        <div class="form-group">
            <label for="expirationDate" class="col-form-label-lg mb-0">有効期間</label>
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="far fa-calendar-times"></i></span>
                </div>
                <input type="text" class="form-control" placeholder="ExpirationDate" aria-label="ExpirationDate" aria-describedby="basic-addon1" value="{{ data.0.expiration_date }}" disabled="disabled">
                <div class="input-group-append">
                    <button type="submit" class="btn btn-outline-secondary" name="updateExpirationDate">更新</button>
                </div>
            </div>
            <p class="text-danger">※有効期間満了後の各種データの保有期間は満了から1ヶ月となります</p>
        </div>

        {% comment %} <label>有効期限</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="far fa-calendar-times"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="ExpirationDate" aria-label="ExpirationDate" aria-describedby="basic-addon1" value="{{ data.0.expiration_date }}" disabled="disabled">
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary" name="updateExpirationDate">更新</button>
            </div>
        </div> {% endcomment %}

        {% if data.0.frequency_limit != None %}
        <div class="form-group">
            <label for="expirationDate" class="col-form-label-lg mb-0">有効限度回数</label>
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fas fa-bomb"></i></span>
                </div>
                <input type="text" class="form-control" placeholder="FrequencyLimit" aria-label="FrequencyLimit" aria-describedby="basic-addon1" value="{{ count }} / {{ data.0.frequency_limit }}" disabled="disabled">
            </div>
        </div>
        {% endif %}

        {% comment %} {% if data.0.frequency_limit != None %}
        <label>限度回数</label>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="fas fa-bomb"></i></span>
            </div>
            <input type="text" class="form-control" placeholder="FrequencyLimit" aria-label="FrequencyLimit" aria-describedby="basic-addon1" value="{{ data.0.frequency_limit }}" disabled="disabled">
        </div>
        {% endif %} {% endcomment %}

        <hr>

        <button type="submit" class="btn btn-secondary" name="back"><i class="fas fa-arrow-left fa-fw"></i>戻る</button>

        <div class="modal fade" id="modal0" tabindex="-1" role="dialog" aria-labelledby="modalLabel0" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalLabel0">パスワード変更</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-key"></i><span>
                                </div>
                                <input type="password" class="form-control" id="password" name="password" placeholder="古いパスワードを入力">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-key"></i><span>
                                </div>
                                <input type="password" class="form-control" id="new_password1" name="newPassword1" placeholder="新しいパスワードを入力">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-key"></i><span>
                                </div>
                                <input type="password" class="form-control" id="new_password2" name="newPassword2" placeholder="新しいパスワードを入力（確認用）">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary w-50" data-dismiss="modal">キャンセル</button>
                        <button type="submit" class="btn btn-outline-secondary w-50" name="chgPassword">変更</button>
                    </div>
                </div>
            </div>
        </div>

    </div>
</form>
{% endblock content %}

templates/imagediff/csv.html
{% extends 'imagediff/base.html' %}
{% load i18n static %}

{% block additional_meta %}
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
{% endblock additional_meta %}

{% block title_name %}Csv{% endblock title_name %}

{% block additional_script %}
<link rel="stylesheet" type="text/css" href="{% static "imagediff/css/csv.css" %}">
{% endblock additional_script %}

{% block content %}
{% if messages %}
<ul class="messagelist">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="form-inner">
        <h2 class="display-5">CSVファイル取込</h2>

        <hr>

        <div class="form-group">                
            <label for="id_csvfile" class="col-form-label-lg mb-0">{{ form.csvfile.label }}</label>     
            <small class="text-danger">※ 文字コード：UTF-8 のファイルのみ取込みできます。</small>           
            <div class="input-group input-group-lg">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-lg"><i class="fas fa-file-csv"></i><span>
                </div>
                {{ form.csvfile }}
                <div class="input-group-append">
                    <button type="submit" class="btn btn-secondary" name="readCsv">取込</button>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-form-label-lg mb-0">Step2. 検索ワード列指定</label>
            <div class="container-fluid">
                <div class="row justify-content-between">
                    <div class="custom-control custom-checkbox">
                        {{ form.wordSpaceDelHalf }}
                        <label class="custom-control-label" for="{{ form.wordSpaceDelHalf.auto_id }}">{{ form.wordSpaceDelHalf.label }}</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.wordSpaceDelFull }}
                        <label class="custom-control-label" for="{{ form.wordSpaceDelFull.auto_id }}">{{ form.wordSpaceDelFull.label }}</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.wordSpaceFullToHalf }}
                        <label class="custom-control-label" for="{{ form.wordSpaceFullToHalf.auto_id }}">{{ form.wordSpaceFullToHalf.label }}</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.wordFullToHalf }}
                        <label class="custom-control-label" for="{{ form.wordFullToHalf.auto_id }}">{{ form.wordFullToHalf.label }}</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.wordHalfToFull }}
                        <label class="custom-control-label" for="{{ form.wordHalfToFull.auto_id }}">{{ form.wordHalfToFull.label }}</label>
                    </div>
                    <div class="input-group pl-0 pt-2">
                        <div class="input-group-prepend">
                            <span class="input-group-text">列指定</span>
                        </div>
                        <select name="wordSelectCol" class="custom-select" id="id_wordSelectCol">
                        {% for option in options %}
                            <option value="{{ option.0 }}">{{ option.1 }}</option>
                        {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-form-label-lg mb-0">Step3. コメント列指定</label>
            <div class="container-fluid">
                <div class="row justify-content-between">
                    <div class="custom-control custom-checkbox">
                        {{ form.cmtSpaceDelHalf }}
                        <label class="custom-control-label" for="{{ form.cmtSpaceDelHalf.auto_id }}">{{ form.cmtSpaceDelHalf.label }}</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.cmtSpaceDelFull }}
                        <label class="custom-control-label" for="{{ form.cmtSpaceDelFull.auto_id }}">{{ form.cmtSpaceDelFull.label }}</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.cmtSpaceFullToHalf }}
                        <label class="custom-control-label" for="{{ form.cmtSpaceFullToHalf.auto_id }}">{{ form.cmtSpaceFullToHalf.label }}</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.cmtFullToHalf }}
                        <label class="custom-control-label" for="{{ form.cmtFullToHalf.auto_id }}">{{ form.cmtFullToHalf.label }}</label>
                    </div>
                    <div class="custom-control custom-checkbox">
                        {{ form.cmtHalfToFull }}
                        <label class="custom-control-label" for="{{ form.cmtHalfToFull.auto_id }}">{{ form.cmtHalfToFull.label }}</label>
                    </div>
                    <div class="input-group pl-0 pt-2">
                        <div class="input-group-prepend">
                            <span class="input-group-text">列指定</span>
                        </div>
                        <select name="cmtSelectCol" class="custom-select" id="id_cmtSelectCol">
                        {% for option in options %}
                            <option value="{{ option.0 }}">{{ option.1 }}</option>
                        {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label class="col-form-label-lg mb-0">Step4. 警告DBへ追加</label>
            <div class="container-fluid">
                <div class="row justify-content-between">
                    <div class="custom-control custom-checkbox">
                        {{ form.addAlertDBIndexDel }}
                        <label class="custom-control-label" for="{{ form.addAlertDBIndexDel.auto_id }}">{{ form.addAlertDBIndexDel.label }}</label>
                    </div>
                    <button type="submit" class="btn btn-secondary mt-2" name="addAlertDB">実行</button>
                </div>
            </div>
            <div class="text-right"><small class="text-danger">※ 検索ワードに指定した列に重複があった場合、重複行は除外されます。</small></div>
        </div>

        <table class="table table-striped">
            <thead class="thead-light">
                <tr>
                {% for r in rows.0 %}
                    <th><div class="text-center">{{ forloop.counter }}列目</div></th>
                {% endfor %}
                </tr>
            </thead>
            <tbody>
            {% for row in rows %}
                <tr>
                {% for r in row %}
                    <td>{{ r }}</td>
                {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <small class="text-danger">※ 先頭から10行まで表示しています。</small>

        <hr>

        <button type="submit" class="btn btn-secondary" name="back"><i class="fas fa-arrow-left fa-fw"></i>戻る</button>

    </div>
</form>
{% endblock content %}